name: cell test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  cell_test:
    name: jest cell test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: npm install
        run: npm install
      - name: npm test
        run: npm test